modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="washthesky"
version="1.0.2"
displayName="WashTheSky"
credits="Created using MCreator"
displayURL="https://www.curseforge.com/minecraft/mc-mods/washthesky"
updateJSONURL="https://gist.github.com/J0J0HA/438c24160880a675681f19bf23395fa5/raw"
authors="JoJoJux/Johannes K. H."
description='''
This mod is an alternative skyblock starter mod.
'''

[[dependencies.washthesky]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




